---
- name: playbook1
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:

  - name: Ensure grub file is changed
    lineinfile:
      path: ./grub
      regexp:  '^(GRUB_CMDLINE_LINUX=.*)(net\.ifnames=[0-9])(.*)'
      line:  '\1net.ifnames=0\3'
      # regexp: '^GRUB_CMDLINE_LINUX='
      # line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      backrefs: yes
      backup: yes

  - name: Ensure grub file is changed
    lineinfile:
      path: ./grub
      regexp: '^(GRUB_CMDLINE_LINUX=.*)(biosdevname=[0-9])(.*)'
      line: '\1biosdevname=0\3'
      backrefs: yes

  - name: Update grub
    shell:
      cmd: 'grub2-mkconfig -o /boot/grub2/grub.cfg'
...