---
- name: playbook2
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Ensure httpd is absented
    package:
      name: httpd
      state: absent

  - name: Ensure file is absent
    file:
      path: /var/www/html/index.html
      state: absent
  
  - name: Ensure firewall closed port
    firewalld:
      port: 80/tcp
      state: disabled
...