---
- name: playbook1
  hosts: nodes
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: Ensure httpd and firewalld are presented
    package:
      name:
      - httpd
      - firewalld
      state: present

  - name: Ensure service httpd is started
    service:
      name: httpd
      state: started

  - name: Esure html file is copied
    copy:
      src: example.html
      dest: /var/www/html/index.html

  - name: Ensure service firewalld is started
    service:
      name: firewalld
      state: started

  - name: Ensure firewall allowed connection
    firewalld:
      port: 80/tcp
      state: enabled
...